config/routes.rb
ChatApp::Application.routes.draw do
  get "users/new"
  get "sessions/new"
  get "sign_out", to: "sessions_#destroy", as: "sign_out"
  post "sessions", to: "sessions#create"
  post "users", to: "users#create"

  resources :clowds


  root to: 'static_pages#home'
  get 'home', to: 'posts#home'
  get 'faq', to: 'static_pages#faq' 
  get 'about', to: 'static_pages#about' 
  get 'terms', to: 'static_pages#terms' 
  get 'contact', to: 'static_pages#contact' 
  post 'verify_status', to: 'static_pages#verify_status'
end

app/models/clowd.rb
class Clowd
    include Mongoid::Document
    include Mongoid::Timestamps

    field :name, type: String
    field :description, type: String
    field :edit, type: Time
    field :approvals, type: Integer
    field :flags, type: Integer
    field :status, type: Integer
    field :icon, type: String
end

app/models/user.rb
class User
    include Mongoid::Document
    field :username, type: String
    field :email, type: String
    field :password_hash, type: String
    field :password_salt, type: String
    
    attr_accessor :password
    validates_uniqueness_of :username
    validates_uniqueness_of :email
    validates_length_of :username, {minimum: 6, maximum: 20}
    validates_length_of :password, {minimum: 6, maximum: 20}
    validates_confirmation_of :password
    validates_presence_of :password

    attr_accessible :username, :email, :password, :password_confirmation


    before_save :encrypt_password

    #class methods
    class << self
        def authenticate(username, password)
            user = User.find_by(username: username)    
            if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
                user
            else
                nil
            end
        end

    end

    def encrypt_password
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    protect_from_forgery

    def current_user
        @current_user ||= User.find_by(username: session[:username]) if session[:username]
    end
end

app/controllers/clowds_controller.rb
class ClowdsController < ApplicationController
  # GET /clowds
  # GET /clowds.json
  def index
    @clowds = Clowd.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clowds }
    end
  end

  # GET /clowds/1
  # GET /clowds/1.json
  def show
    @clowd = Clowd.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clowd }
    end
  end

  # GET /clowds/new
  # GET /clowds/new.json
  def new
    @clowd = Clowd.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clowd }
    end
  end

  # GET /clowds/1/edit
  def edit
    @clowd = Clowd.find(params[:id])
  end

  # POST /clowds
  # POST /clowds.json
  def create
    @clowd = Clowd.new(params[:clowd])

    respond_to do |format|
      if @clowd.save
        format.html { redirect_to @clowd, notice: 'Clowd was successfully created.' }
        format.json { render json: @clowd, status: :created, location: @clowd }
      else
        format.html { render action: "new" }
        format.json { render json: @clowd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clowds/1
  # PUT /clowds/1.json
  def update
    @clowd = Clowd.find(params[:id])

    respond_to do |format|
      if @clowd.update_attributes(params[:clowd])
        format.html { redirect_to @clowd, notice: 'Clowd was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clowd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clowds/1
  # DELETE /clowds/1.json
  def destroy
    @clowd = Clowd.find(params[:id])
    @clowd.destroy

    respond_to do |format|
      format.html { redirect_to clowds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    layout 'logged'
  def verified_home
    if !cookies.signed[:in_boston]
      redirect_to(root_url)
    else


    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        respond_to do |f|
           f.html { redirect_to home_url }
           f.js
        end
    end

    def create
        user = User.authenticate(params[:username], params[:password])        
        if user
            session[:username] = params[:username]
            @status = 1
        else
            @status = 0 
        end

        respond_to do |f|
            f.html { redirect_to home_url }
            f.js
        end
    end

    def destroy
        session.clear
        redirect_to home_url
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    #temp to test features prior to verification
    cookies.delete :in_boston
    
    if cookies.signed[:in_boston]
      headers["Status"] = "301 Moved Permanently"
      redirect_to(home_url)
    else
        #redirect because geolocation doesn't work right now.        
    end
  end
  
  def verify_status
    lat = params[:verify_lat]
    long = params[:verify_long]

    #geocode latitude and longitude using Open MQ Geocoding API
    app_key = "Fmjtd%7Cluub25ub2g%2C2n%3Do5-9u851f" 
    response = HTTParty.get("http://open.mapquestapi.com/geocoding/v1/reverse?key=" + app_key + "&outFormat=json&location=#{lat},#{long}")
    #parse response and determine if user is in the right city
    place = response["results"][0]["locations"][0]

    #tentatively Hong Kong for testing purposes
    city = "Baltimore"

    if place["adminArea5"].include?(city) || place["adminArea4"].include?(city) || place["adminArea3"].include?(city) || place["adminArea1"].include?(city)
      cookies.permanent.signed[:in_boston] = true

      #redirect to verified page
      headers["Status"] = "301 Moved Permanently"
      flash[:success] = "Welcome to Clowder!"
      redirect_to(home_url)
    else
      flash[:block] = "Sorry, we do not support your location yet. Check back later!"
      redirect_to(root_url)
    end 

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    layout false
    def new
        @user = User.new                
        respond_to do |f|
            f.html { redirect_to home_url }
            f.js
        end
    end
    def create
        @user = User.new(params[:user])
        if @user.save
            session[:username] = params[:user][:username]
        end

        respond_to do |f|
            f.html { redirect_to home_url }
            f.js
        end

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clowds_helper.rb
module ClowdsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clowds/_form.html.erb
<%= form_for(@clowd) do |f| %>
  <% if @clowd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clowd.errors.count, "error") %> prohibited this clowd from being saved:</h2>

      <ul>
      <% @clowd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :edit %><br />
    <%= f.datetime_select :edit %>
  </div>
  <div class="field">
    <%= f.label :approvals %><br />
    <%= f.number_field :approvals %>
  </div>
  <div class="field">
    <%= f.label :flags %><br />
    <%= f.number_field :flags %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :icon %><br />
    <%= f.text_field :icon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clowds/edit.html.erb
<h1>Editing clowd</h1>

<%= render 'form' %>

<%= link_to 'Show', @clowd %> |
<%= link_to 'Back', clowds_path %>

app/views/clowds/index.html.erb
<h1>Listing clowds</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Edit</th>
    <th>Approvals</th>
    <th>Flags</th>
    <th>Status</th>
    <th>Icon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clowds.each do |clowd| %>
  <tr>
    <td><%= clowd.name %></td>
    <td><%= clowd.description %></td>
    <td><%= clowd.edit %></td>
    <td><%= clowd.approvals %></td>
    <td><%= clowd.flags %></td>
    <td><%= clowd.status %></td>
    <td><%= clowd.icon %></td>
    <td><%= link_to 'Show', clowd %></td>
    <td><%= link_to 'Edit', edit_clowd_path(clowd) %></td>
    <td><%= link_to 'Destroy', clowd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clowd', new_clowd_path %>

app/views/clowds/new.html.erb
<h1>New clowd</h1>

<%= render 'form' %>

<%= link_to 'Back', clowds_path %>

app/views/clowds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @clowd.name %>
</p>

<p>
  <b>Description:</b>
  <%= @clowd.description %>
</p>

<p>
  <b>Edit:</b>
  <%= @clowd.edit %>
</p>

<p>
  <b>Approvals:</b>
  <%= @clowd.approvals %>
</p>

<p>
  <b>Flags:</b>
  <%= @clowd.flags %>
</p>

<p>
  <b>Status:</b>
  <%= @clowd.status %>
</p>

<p>
  <b>Icon:</b>
  <%= @clowd.icon %>
</p>


<%= link_to 'Edit', edit_clowd_path(@clowd) %> |
<%= link_to 'Back', clowds_path %>

app/views/layouts/_foot.html.erb
<footer class = "container">
  <div class = "row text-center">
    <span class = "sub-text">All Rights Reserved Clowder 2013 &copy;</span>
  </div>
  <div class = "row text-center">
    <a href = "/about">About</a> &nbsp; &nbsp;
    <a href = "/terms">Terms</a> &nbsp; &nbsp;
    <a href = "/contact">Contact</a> &nbsp; &nbsp;
  </div>
</footer>

app/views/layouts/_head.html.erb
<header class = "container">
  <div class = "row">
    <div class = "span4 offset8">
      <div class = "pull-right button-bar">
        <ul class = "nav nav-pills">
          <li <% if yield(:title) == "Home" %> class = "active" <% end %>><a href = "/<% if cookies.signed[:in_boston] %>home<% end %>">Home</a></li>
          &nbsp; &nbsp;
          <li <% if yield(:title) == "FAQ" %> class = "active" <% end %>><a href = "/faq">FAQ</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class = "row text-center" id = "flash-alerts">
    <% flash.each do |k,v| %>
      <%= content_tag(:div, v, class: "alert alert-#{k}") %>
    <% end %>
  </div>
</header>

app/views/layouts/_logged_foot.html.erb
<footer class = "container">
  <div class = "row text-center">
    <span class = "sub-text">All Rights Reserved Clowder 2013 &copy;</span>
  </div>
  <div class = "row text-center">
    <a href = "/about">About</a> &nbsp; &nbsp;
    <a href = "/terms">Terms</a> &nbsp; &nbsp;
    <a href = "/contact">Contact</a> &nbsp; &nbsp;
  </div>
</footer>

app/views/layouts/_logged_head.html.erb
<div class = "navbar-fixed-top top-bar-background"></div>
<header class = "navbar-fixed-top">
<div class = "container-fluid" style = "padding-top:50px;">
  <div class = "row-fluid">
    <div class = "span3">
      <h1 class = "pull-right">Clowder</h1>
    </div>
    <div class = "span7" style = "padding-top:15px;">
      <div class = "input-append search-div text-center">
      <input type = "text" placeholder = "Search for places or clowds" class = "search-field">
      <button class = "btn">Search</button>
      </div>
    </div>
    <div class = "span2" style = "display:table; height: 60px;">
      <div style = "display: table-cell; vertical-align: middle">
        <% if current_user %>
           Not <%= current_user.username %>?<br /> <a href = "<%= sign_out_path %>">Sign out</a>. 
        <% else %>
            <a id = "login_link" href = "#">Login</a> or <a id = "register_link" href = "#">Register</a>
        <% end %>
      </div>
    </div>
  </div>
</div>
</header>
<div id = "dimmer"></div>
<div id = "dimmed_display">
<div class = "text-center dimmed_load">Loading...</div></div>

app/views/layouts/_popup.html.erb
<button id = "dimmer_close" class = "close pull-right">&times;</button>
<div class = "popup-content">
    <h2 class = "popup-title pull-left"><%= content_for :heading %></h2>

    <div class = "clear-floats">
    <%= yield %>
    </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang = "en">
<head>
  <title>ChatApp | <%= yield(:title) %></title>
  <%= stylesheet_link_tag params[:controller], :media => "all" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/head' %>
<%= yield %>
<%= render 'layouts/foot' %>
<%= javascript_include_tag params[:controller] %>
</body>
</html>

app/views/layouts/logged.html.erb
<!DOCTYPE html>
<html lang = "en">
<head>
  <title>Clowder | <%= yield(:title) %></title>
  <%= stylesheet_link_tag params[:controller], :media => "all" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/logged_head' %>
<%= yield %>
<%= javascript_include_tag params[:controller] %>
</body>
</html>

app/views/posts/home.html.erb
<%= provide(:title, 'Home') %>
<div id = "load-left">
<div class = "load-left-text">
Loading Posts...
</div>
</div>
<div class = "left-container">
    <!--Main post box-->
    <div class = "text-container">
        <div class = "depth-label">General /</div>
        <div class = "post-writer-container">
            <textarea id = "post-writer" placeholder = "Post, Chat, or Share a pic!"></textarea>
        </div>

        <div class = "posts-container">

            <div class = "post">
                <div class = "post-left">
                    <div class = "post-top text-left">
                        <div class = "line-container">
                        <span class = "line-text pull-left post-clowd">
                            Starbucks
                        </span>
                        </div>
                    </div>
                    <div class = "post-mid post-content">
                        <h2 class = "post-title">This is a post. This is a post!</h2>
                    </div>
                    <div class = "post-bot">
                        <span class = "pull-left">
                            <span class = "user-name">ian-lee</span> <i class = "post-time">(3 hours ago)</i> 
                        </span>
                        <span class = "pull-right">
                            <a href = "#" class = "post-link">300 Responses</a> &nbsp; &nbsp; <a href = "#" class = "post-link">Reply</a>
                        </span>
                    </div>
                </div>
                <div class = "post-center">
                    <div class = "post-top text-right pos-rating">
                        1924
                    </div>
                    <div class = "post-bot text-right neg-rating">
                        657
                    </div>

                </div>
                <div class = "post-right">
                    <div class = "post-top">
                        <div class = "vote-button">
                            <i class = "icon-chevron-up icon-white"></i>
                        </div>
                    </div>
                    <div class = "post-mid">
                       <div class = "rating-bar">&nbsp;</div> 
                       <div class = "rating-bar-fill">&nbsp;</div> 
                       <div class = "rating-overlay">30%</div>
                    </div>
                    <div class = "post-bot">
                        <div class = "vote-button">
                            <i class = "icon-chevron-down icon-white"></i>
                        </div>
                    </div>
                </div>
            </div>

            <div class = "post">
                <div class = "post-left">
                    <div class = "post-top text-left">
                        <div class = "line-container">
                        <span class = "line-text pull-left post-clowd">
                            Starbucks
                        </span>
                        </div>
                    </div>
                    <div class = "post-mid post-content">
                        <h2 class = "post-title">This is another post. It is also a post!</h2>
                    </div>
                    <div class = "post-bot">
                        <span class = "pull-left">
                            <span class = "user-name">ian-lee</span> <i class = "post-time">(3 hours ago)</i> 
                        </span>
                        <span class = "pull-right">
                            <a href = "#" class = "post-link">300 Responses</a> &nbsp; &nbsp; <a href = "#" class = "post-link">Reply</a>
                        </span>
                    </div>
                </div>
                <div class = "post-center">
                    <div class = "post-top text-right pos-rating">
                        1924
                    </div>
                    <div class = "post-bot text-right neg-rating">
                        657
                    </div>

                </div>
                <div class = "post-right">
                    <div class = "post-top">
                        <div class = "vote-button">
                            <i class = "icon-chevron-up icon-white"></i>
                        </div>
                    </div>
                    <div class = "post-mid">
                       <div class = "rating-bar">&nbsp;</div> 
                       <div class = "rating-bar-fill">&nbsp;</div> 
                       <div class = "rating-overlay">30%</div>
                    </div>
                    <div class = "post-bot">
                        <div class = "vote-button">
                            <i class = "icon-chevron-down icon-white"></i>
                        </div>
                    </div>
                </div>
            </div>


            <div class = "post">
                <div class = "post-left">
                    <div class = "post-top text-left">
                        <div class = "line-container">
                        <span class = "line-text pull-left post-clowd">
                            Starbucks
                        </span>
                        </div>
                    </div>
                    <div class = "post-mid post-content">
                        <h2 class = "post-title">Wooo look at me.... I'm an attention whoreeeee whooopeee!!!</h2>
                    </div>
                    <div class = "post-bot">
                        <span class = "pull-left">
                            <span class = "user-name">ian-lee</span> <i class = "post-time">(3 hours ago)</i> 
                        </span>
                        <span class = "pull-right">
                            <a href = "#" class = "post-link">300 Responses</a> &nbsp; &nbsp; <a href = "#" class = "post-link">Reply</a>
                        </span>
                    </div>
                </div>
                <div class = "post-center">
                    <div class = "post-top text-right pos-rating">
                        1924
                    </div>
                    <div class = "post-bot text-right neg-rating">
                        657
                    </div>

                </div>
                <div class = "post-right">
                    <div class = "post-top">
                        <div class = "vote-button">
                            <i class = "icon-chevron-up icon-white"></i>
                        </div>
                    </div>
                    <div class = "post-mid">
                       <div class = "rating-bar">&nbsp;</div> 
                       <div class = "rating-bar-fill">&nbsp;</div> 
                       <div class = "rating-overlay">30%</div>
                    </div>
                    <div class = "post-bot">
                        <div class = "vote-button">
                            <i class = "icon-chevron-down icon-white"></i>
                        </div>
                    </div>
                </div>
            </div>

            <div class = "post">
                <div class = "post-left">
                    <div class = "post-top text-left">
                        <div class = "line-container">
                        <span class = "line-text pull-left post-clowd">
                            Starbucks
                        </span>
                        </div>
                    </div>
                    <div class = "post-mid post-content">
                        <h2 class = "post-title">YEEEEE oooooohhhh yeaaaahhhh yeyeyeyeyeye heeeeeeeeeeeeeeeeeeeeeeeeey theree what's up man</h2>
                    </div>
                    <div class = "post-bot">
                        <span class = "pull-left">
                            <span class = "user-name">ian-lee</span> <i class = "post-time">(3 hours ago)</i> 
                        </span>
                        <span class = "pull-right">
                            <a href = "#" class = "post-link">300 Responses</a> &nbsp; &nbsp; <a href = "#" class = "post-link">Reply</a>
                        </span>
                    </div>
                </div>
                <div class = "post-center">
                    <div class = "post-top text-right pos-rating">
                        1924
                    </div>
                    <div class = "post-bot text-right neg-rating">
                        657
                    </div>

                </div>
                <div class = "post-right">
                    <div class = "post-top">
                        <div class = "vote-button">
                            <i class = "icon-chevron-up icon-white"></i>
                        </div>
                    </div>
                    <div class = "post-mid">
                       <div class = "rating-bar">&nbsp;</div> 
                       <div class = "rating-bar-fill">&nbsp;</div> 
                       <div class = "rating-overlay">30%</div>
                    </div>
                    <div class = "post-bot">
                        <div class = "vote-button">
                            <i class = "icon-chevron-down icon-white"></i>
                        </div>
                    </div>
                </div>
            </div>

            <div class = "post">
                <div class = "post-left">
                    <div class = "post-top text-left">
                        <div class = "line-container">
                        <span class = "line-text pull-left post-clowd">
                            Starbucks
                        </span>
                        </div>
                    </div>
                    <div class = "post-mid post-content">
                        <h2 class = "post-title">YEEEEE oooooohhhh yeaaaahhhh</h2>
                    </div>
                    <div class = "post-bot">
                        <span class = "pull-left">
                            <span class = "user-name">ian-lee</span> <i class = "post-time">(3 hours ago)</i> 
                        </span>
                        <span class = "pull-right">
                            <a href = "#" class = "post-link">300 Responses</a> &nbsp; &nbsp; <a href = "#" class = "post-link">Reply</a>
                        </span>
                    </div>
                </div>
                <div class = "post-center">
                    <div class = "post-top text-right pos-rating">
                        1924
                    </div>
                    <div class = "post-bot text-right neg-rating">
                        657
                    </div>

                </div>
                <div class = "post-right">
                    <div class = "post-top">
                        <div class = "vote-button">
                            <i class = "icon-chevron-up icon-white"></i>
                        </div>
                    </div>
                    <div class = "post-mid">
                       <div class = "rating-bar">&nbsp;</div> 
                       <div class = "rating-bar-fill">&nbsp;</div> 
                       <div class = "rating-overlay">30%</div>
                    </div>
                    <div class = "post-bot">
                        <div class = "vote-button">
                            <i class = "icon-chevron-down icon-white"></i>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class = "right-container">
    <div class = "expand-bar">
    <!--Expand bar-->
         <div id = "expand-icons">
             <i class = "icon-arrow-left"></i>
             <br />
             <i class = "icon-arrow-left"></i>
             <br />
             <i class = "icon-arrow-left"></i>
         </div>
    </div>
    <div class = "map-box">
    <!--Map box-->
        <div id = "map">
           <div class = "map-placeholder">Loading Maps...</div>
        </div>
    </div>
    <div class = "suggest-box">
    <!--Clowd suggestion box-->
        <div class = "suggest-inner-box">
            <div class = "text-container">
                <h4 class = "suggest-title">Nearby Clowds</h4>
                <ul class = "clowd-listing">
                    <li><a href= "#">Goldman Sachs</a></li>
                    <li><a href= "#">Chinese International School</a></li>
                    <li><a href= "#">Starbucks</a></li>
                    <li><a href= "#">Socialito</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<section class = "main-body">
  <div class = "container">
    <div class = "row">
      <h1 class = "static-title">About</h1>
      <div class = "descriptive-text">
        <p>
          Proin vitae lacinia risus. Morbi lorem nisl, ornare at ultricies id, bibendum nec sapien. Proin diam orci, viverra vel nibh vel, vulputate varius lacus. Sed nec orci luctus, imperdiet lacus non, ultricies massa. Praesent odio eros, auctor non ligula ac, gravida porta tellus. Pellentesque sem urna, pharetra eget pellentesque non, euismod ac augue. Nullam aliquam tellus eget lacus ornare, in dignissim augue iaculis. Morbi sed placerat erat. Suspendisse at leo vel leo vestibulum pretium. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
        </p>
        <p>
          Donec in mauris tortor. Proin quis placerat est. Suspendisse cursus urna eget est pharetra, eget tincidunt orci varius. Nulla dignissim at elit a aliquet. Ut et cursus erat. Phasellus a turpis purus. Suspendisse at congue eros. Nullam mollis, odio ac mollis porta, nunc ipsum molestie diam, eu egestas lacus mi non erat.
        </p>
        <p>
          In ullamcorper commodo sapien, aliquet porttitor ante scelerisque venenatis. Maecenas volutpat arcu dapibus lectus imperdiet viverra. Aliquam viverra nisl massa, et posuere diam lacinia at. Quisque commodo convallis mi id condimentum. Mauris ullamcorper libero sit amet purus blandit accumsan. Etiam egestas, lacus eu viverra malesuada, augue ante accumsan nisi, vel pharetra dolor enim nec lectus. Mauris eget lectus elit. Praesent et pulvinar nibh.
        </p>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<section class = "main-body">
  <div class = "container">
    <div class = "row">
      <h1 class = "static-title">Contact</h1>
      <div class = "descriptive-text">
        <p>
          Proin vitae lacinia risus. Morbi lorem nisl, ornare at ultricies id, bibendum nec sapien. Proin diam orci, viverra vel nibh vel, vulputate varius lacus. Sed nec orci luctus, imperdiet lacus non, ultricies massa. Praesent odio eros, auctor non ligula ac, gravida porta tellus. Pellentesque sem urna, pharetra eget pellentesque non, euismod ac augue. Nullam aliquam tellus eget lacus ornare, in dignissim augue iaculis. Morbi sed placerat erat. Suspendisse at leo vel leo vestibulum pretium. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
        </p>
        <p>
          Donec in mauris tortor. Proin quis placerat est. Suspendisse cursus urna eget est pharetra, eget tincidunt orci varius. Nulla dignissim at elit a aliquet. Ut et cursus erat. Phasellus a turpis purus. Suspendisse at congue eros. Nullam mollis, odio ac mollis porta, nunc ipsum molestie diam, eu egestas lacus mi non erat.
        </p>
        <p>
          In ullamcorper commodo sapien, aliquet porttitor ante scelerisque venenatis. Maecenas volutpat arcu dapibus lectus imperdiet viverra. Aliquam viverra nisl massa, et posuere diam lacinia at. Quisque commodo convallis mi id condimentum. Mauris ullamcorper libero sit amet purus blandit accumsan. Etiam egestas, lacus eu viverra malesuada, augue ante accumsan nisi, vel pharetra dolor enim nec lectus. Mauris eget lectus elit. Praesent et pulvinar nibh.
        </p>
      </div>
    </div>
  </div>
</section>

app/views/users/_reg.html.erb
<% content_for :heading do %>
Register
<% end %>

<%= form_for @user, url: {action: "create"} do |form| %>



<%= form.label :username %>
<%= form.text_field :username, autocomplete: :off %>

<br />

<%= form.label :email, "Your .edu e-mail" %>
<%= form.text_field :email, autocomplete: :off %>

<br />

<%= form.label :password %>
<%= form.password_field :password %>

<br />

<%= form.label :password_confirmation %>
<%= form.password_field :password_confirmation %>

<br />
<br />

<%= form.submit "Sign up", class: "c-btn" %>
<% end %>